# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0dec56c4957bb87b29a74ad971449f63b45e35857b6a43a3dbddc84b268705428ae64ed0c5cdb3bf276fde7002d7d66769be9aad132602b15d05fefc48659e3

test:
  secret_key_base: 1c0145f5e65d07e846d0ddd74a66f25e04469ea2eba6b9eb35e7a91f41c563a4e7a5acdb27ed273dfac841daf99117d821c3095e2ae12b33bb492d994b8a62b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
